name: Package

on:
  pull_request:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Determine version
        if: ${{github.event_name == 'pull_request'}}
        id: version
        uses: codacy/git-version@2.8.0
      - name: Write version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src/streamdeck.json
          field: version
          value: ${{github.event.release.name || steps.version.outputs.version}}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Package
        run: npm run package
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.mediabounds.streamdeck.jira-${{github.event.release.name || steps.version.outputs.version}}.streamDeckPlugin
          path: release/com.mediabounds.streamdeck.jira.streamDeckPlugin
          if-no-files-found: error
      - name: Publish
        if: ${{github.event_name == 'release'}}
        uses: softprops/action-gh-release@v2
        with:
          files: release/com.mediabounds.streamdeck.jira.streamDeckPlugin
